import type { Participant } from '@azavista/advanced-search'
import type { PuckEditorDictionary, PuckEditorLanguage, PuckEditorMetadata } from 'lib/components/PuckEditor/type'
import type { Asset, Event } from 'lib/shared/types'

export const participant: Participant = {
  "id": "67da68de47ced642cb59160e",
  "event_id": "64145d37103a8edfd98bec44",
  "stage_id": "64145d5575a4c8db9f1002cc",
  "crm_contact_id": "67da68dedb91062fd83c2d7d",
  "external_id": null,
  "created_at": "2025-03-19T06:49:02.729Z",
  "updated_at": "2025-08-04T23:04:06.639Z",
  "team_ids": [
    253,
    254,
    267,
    277
  ],
  "organization_manager": true,
  "additional_info_68": "sd",
  "organization_id": "643e3aac031f8ab12b01ff2b",
  "approver_email": "shulha.yahya+paid_manager@azavista.com",
  "registrationtime__w": "2025-05-02T13:32:11.811Z",
  "document_upload__crm": "6819f22162e7286c60af8255",
  "multiselect__crm": [
    "One",
    "Two",
    "4"
  ],
  "first_name": "manager",
  "i_am_over_18_years_old__crm": true,
  "last_name": "mg",
  "email": "shulha.yahya+paid_manager@azavista.com",
  "favorite_color": "Red",
  "preferred_language": "en-US",
  "profile_image": "688873e877a9907ddbbd28ba",
  "crmstatus": "registered"
}

export const event: Event = {
  "id": "64145d37103a8edfd98bec44",
  "series_id": null,
  "sequence_id": null,
  "external_id": null,
  "team_ids": [
    253,
    254,
    277
  ],
  "type": "event",
  "settings": {
    "access": "public",
    "languages": [
      "en-US",
      "nl-NL",
      "fr-FR",
      "de-DE",
      "it-IT",
      "es-ES",
      "uk-UA"
    ],
    "authorization": "link",
    "publish": "published",
    "last_registration_date": null,
    "publication_date": null,
    "offline_date": null,
    "datetime_format": "LLL",
    "date_format": "MM-DD-YYYY",
    "time_format": "HH:mm",
    "modules": [
      "participants"
    ],
    "participant_teams": true,
    "duplicate_email": false,
    "url": "/w/event/64145d37103a8edfd98bec44"
  },
  "created_at": "2023-03-17T12:29:43.513Z",
  "updated_at": "2025-08-04T23:04:07.594Z",
  "timezone": "US/Mountain",
  "start": "2023-04-05T00:00:00.000Z",
  "end": "2027-12-31T09:00:00.000Z",
  "reference_number": "dsf",
  "number_field": 2,
  "week_availability__local": [
    "Weekend",
    "Weekday"
  ],
  "name": "Paid",
  "event_url": "https://3.0.devk8s.azavista.com/event/dashboard?eventId=64145d37103a8edfd98bec44&type=event",
  "description": "gh"
 };

export const dictionary: PuckEditorDictionary = {
  en_us: {
    good: 'good',
    save: 'save',
  },
  id_id: {
    good: 'bagus',
    save: 'simpan',
  },
}

export const languages: PuckEditorLanguage[] = [
  {
    id: 'en_us',
    label: 'English',    
  },
  {
    id: 'id_id',
    label: 'Indonesia'
  }
]

const eventFields = [
  {
    "id": "63e50a55a2aaee1f46805437",
    "name": "name",
    "label": "Name",
    "category": "Basic information",
    "schema": {
      "type": "string"
    },
    "type": "string",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.561Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f46805438",
    "name": "start",
    "label": "Start",
    "category": "Basic information",
    "schema": {
      "type": "string",
      "format": "date-time"
    },
    "type": "datetime",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.562Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f46805439",
    "name": "end",
    "label": "End",
    "category": "Basic information",
    "schema": {
      "type": "string",
      "format": "date-time"
    },
    "type": "datetime",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.562Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f4680543a",
    "name": "timezone",
    "label": "Timezone",
    "category": "Basic information",
    "schema": {
      "type": "string",
      "enum": [
        "Africa/Abidjan",
        "Africa/Accra",
        "Africa/Addis_Ababa",
        "Africa/Algiers",
        "Africa/Asmara",
        "Africa/Asmera",
        "Africa/Bamako",
        "Africa/Bangui",
        "Africa/Banjul",
        "Africa/Bissau",
        "Africa/Blantyre",
        "Africa/Brazzaville",
        "Africa/Bujumbura",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/Conakry",
        "Africa/Dakar",
        "Africa/Dar_es_Salaam",
        "Africa/Djibouti",
        "Africa/Douala",
        "Africa/El_Aaiun",
        "Africa/Freetown",
        "Africa/Gaborone",
        "Africa/Harare",
        "Africa/Johannesburg",
        "Africa/Juba",
        "Africa/Kampala",
        "Africa/Khartoum",
        "Africa/Kigali",
        "Africa/Kinshasa",
        "Africa/Lagos",
        "Africa/Libreville",
        "Africa/Lome",
        "Africa/Luanda",
        "Africa/Lubumbashi",
        "Africa/Lusaka",
        "Africa/Malabo",
        "Africa/Maputo",
        "Africa/Maseru",
        "Africa/Mbabane",
        "Africa/Mogadishu",
        "Africa/Monrovia",
        "Africa/Nairobi",
        "Africa/Ndjamena",
        "Africa/Niamey",
        "Africa/Nouakchott",
        "Africa/Ouagadougou",
        "Africa/Porto-Novo",
        "Africa/Sao_Tome",
        "Africa/Timbuktu",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Africa/Windhoek",
        "America/Adak",
        "America/Anchorage",
        "America/Anguilla",
        "America/Antigua",
        "America/Araguaina",
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/ComodRivadavia",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "America/Aruba",
        "America/Asuncion",
        "America/Atikokan",
        "America/Atka",
        "America/Bahia",
        "America/Bahia_Banderas",
        "America/Barbados",
        "America/Belem",
        "America/Belize",
        "America/Blanc-Sablon",
        "America/Boa_Vista",
        "America/Bogota",
        "America/Boise",
        "America/Buenos_Aires",
        "America/Cambridge_Bay",
        "America/Campo_Grande",
        "America/Cancun",
        "America/Caracas",
        "America/Catamarca",
        "America/Cayenne",
        "America/Cayman",
        "America/Chicago",
        "America/Chihuahua",
        "America/Ciudad_Juarez",
        "America/Coral_Harbour",
        "America/Cordoba",
        "America/Costa_Rica",
        "America/Creston",
        "America/Cuiaba",
        "America/Curacao",
        "America/Danmarkshavn",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Denver",
        "America/Detroit",
        "America/Dominica",
        "America/Edmonton",
        "America/Eirunepe",
        "America/El_Salvador",
        "America/Ensenada",
        "America/Fort_Nelson",
        "America/Fort_Wayne",
        "America/Fortaleza",
        "America/Glace_Bay",
        "America/Godthab",
        "America/Goose_Bay",
        "America/Grand_Turk",
        "America/Grenada",
        "America/Guadeloupe",
        "America/Guatemala",
        "America/Guayaquil",
        "America/Guyana",
        "America/Halifax",
        "America/Havana",
        "America/Hermosillo",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Indianapolis",
        "America/Inuvik",
        "America/Iqaluit",
        "America/Jamaica",
        "America/Jujuy",
        "America/Juneau",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/Knox_IN",
        "America/Kralendijk",
        "America/La_Paz",
        "America/Lima",
        "America/Los_Angeles",
        "America/Louisville",
        "America/Lower_Princes",
        "America/Maceio",
        "America/Managua",
        "America/Manaus",
        "America/Marigot",
        "America/Martinique",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Mendoza",
        "America/Menominee",
        "America/Merida",
        "America/Metlakatla",
        "America/Mexico_City",
        "America/Miquelon",
        "America/Moncton",
        "America/Monterrey",
        "America/Montevideo",
        "America/Montreal",
        "America/Montserrat",
        "America/Nassau",
        "America/New_York",
        "America/Nipigon",
        "America/Nome",
        "America/Noronha",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Nuuk",
        "America/Ojinaga",
        "America/Panama",
        "America/Pangnirtung",
        "America/Paramaribo",
        "America/Phoenix",
        "America/Port-au-Prince",
        "America/Port_of_Spain",
        "America/Porto_Acre",
        "America/Porto_Velho",
        "America/Puerto_Rico",
        "America/Punta_Arenas",
        "America/Rainy_River",
        "America/Rankin_Inlet",
        "America/Recife",
        "America/Regina",
        "America/Resolute",
        "America/Rio_Branco",
        "America/Rosario",
        "America/Santa_Isabel",
        "America/Santarem",
        "America/Santiago",
        "America/Santo_Domingo",
        "America/Sao_Paulo",
        "America/Scoresbysund",
        "America/Shiprock",
        "America/Sitka",
        "America/St_Barthelemy",
        "America/St_Johns",
        "America/St_Kitts",
        "America/St_Lucia",
        "America/St_Thomas",
        "America/St_Vincent",
        "America/Swift_Current",
        "America/Tegucigalpa",
        "America/Thule",
        "America/Thunder_Bay",
        "America/Tijuana",
        "America/Toronto",
        "America/Tortola",
        "America/Vancouver",
        "America/Virgin",
        "America/Whitehorse",
        "America/Winnipeg",
        "America/Yakutat",
        "America/Yellowknife",
        "Antarctica/Casey",
        "Antarctica/Davis",
        "Antarctica/DumontDUrville",
        "Antarctica/Macquarie",
        "Antarctica/Mawson",
        "Antarctica/McMurdo",
        "Antarctica/Palmer",
        "Antarctica/Rothera",
        "Antarctica/South_Pole",
        "Antarctica/Syowa",
        "Antarctica/Troll",
        "Antarctica/Vostok",
        "Arctic/Longyearbyen",
        "Asia/Aden",
        "Asia/Almaty",
        "Asia/Amman",
        "Asia/Anadyr",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Ashgabat",
        "Asia/Ashkhabad",
        "Asia/Atyrau",
        "Asia/Baghdad",
        "Asia/Bahrain",
        "Asia/Baku",
        "Asia/Bangkok",
        "Asia/Barnaul",
        "Asia/Beirut",
        "Asia/Bishkek",
        "Asia/Brunei",
        "Asia/Calcutta",
        "Asia/Chita",
        "Asia/Choibalsan",
        "Asia/Chongqing",
        "Asia/Chungking",
        "Asia/Colombo",
        "Asia/Dacca",
        "Asia/Damascus",
        "Asia/Dhaka",
        "Asia/Dili",
        "Asia/Dubai",
        "Asia/Dushanbe",
        "Asia/Famagusta",
        "Asia/Gaza",
        "Asia/Harbin",
        "Asia/Hebron",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Hovd",
        "Asia/Irkutsk",
        "Asia/Istanbul",
        "Asia/Jakarta",
        "Asia/Jayapura",
        "Asia/Jerusalem",
        "Asia/Kabul",
        "Asia/Kamchatka",
        "Asia/Karachi",
        "Asia/Kashgar",
        "Asia/Kathmandu",
        "Asia/Katmandu",
        "Asia/Khandyga",
        "Asia/Kolkata",
        "Asia/Krasnoyarsk",
        "Asia/Kuala_Lumpur",
        "Asia/Kuching",
        "Asia/Kuwait",
        "Asia/Macao",
        "Asia/Macau",
        "Asia/Magadan",
        "Asia/Makassar",
        "Asia/Manila",
        "Asia/Muscat",
        "Asia/Nicosia",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Omsk",
        "Asia/Oral",
        "Asia/Phnom_Penh",
        "Asia/Pontianak",
        "Asia/Pyongyang",
        "Asia/Qatar",
        "Asia/Qostanay",
        "Asia/Qyzylorda",
        "Asia/Rangoon",
        "Asia/Riyadh",
        "Asia/Saigon",
        "Asia/Sakhalin",
        "Asia/Samarkand",
        "Asia/Seoul",
        "Asia/Shanghai",
        "Asia/Singapore",
        "Asia/Srednekolymsk",
        "Asia/Taipei",
        "Asia/Tashkent",
        "Asia/Tbilisi",
        "Asia/Tehran",
        "Asia/Tel_Aviv",
        "Asia/Thimbu",
        "Asia/Thimphu",
        "Asia/Tokyo",
        "Asia/Tomsk",
        "Asia/Ujung_Pandang",
        "Asia/Ulaanbaatar",
        "Asia/Ulan_Bator",
        "Asia/Urumqi",
        "Asia/Ust-Nera",
        "Asia/Vientiane",
        "Asia/Vladivostok",
        "Asia/Yakutsk",
        "Asia/Yangon",
        "Asia/Yekaterinburg",
        "Asia/Yerevan",
        "Atlantic/Azores",
        "Atlantic/Bermuda",
        "Atlantic/Canary",
        "Atlantic/Cape_Verde",
        "Atlantic/Faeroe",
        "Atlantic/Faroe",
        "Atlantic/Jan_Mayen",
        "Atlantic/Madeira",
        "Atlantic/Reykjavik",
        "Atlantic/South_Georgia",
        "Atlantic/St_Helena",
        "Atlantic/Stanley",
        "Australia/ACT",
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Canberra",
        "Australia/Currie",
        "Australia/Darwin",
        "Australia/Eucla",
        "Australia/Hobart",
        "Australia/LHI",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/NSW",
        "Australia/North",
        "Australia/Perth",
        "Australia/Queensland",
        "Australia/South",
        "Australia/Sydney",
        "Australia/Tasmania",
        "Australia/Victoria",
        "Australia/West",
        "Australia/Yancowinna",
        "Brazil/Acre",
        "Brazil/DeNoronha",
        "Brazil/East",
        "Brazil/West",
        "CET",
        "CST6CDT",
        "Canada/Atlantic",
        "Canada/Central",
        "Canada/Eastern",
        "Canada/Mountain",
        "Canada/Newfoundland",
        "Canada/Pacific",
        "Canada/Saskatchewan",
        "Canada/Yukon",
        "Chile/Continental",
        "Chile/EasterIsland",
        "Cuba",
        "EET",
        "EST",
        "EST5EDT",
        "Egypt",
        "Eire",
        "Etc/GMT",
        "Etc/GMT+0",
        "Etc/GMT+1",
        "Etc/GMT+10",
        "Etc/GMT+11",
        "Etc/GMT+12",
        "Etc/GMT+2",
        "Etc/GMT+3",
        "Etc/GMT+4",
        "Etc/GMT+5",
        "Etc/GMT+6",
        "Etc/GMT+7",
        "Etc/GMT+8",
        "Etc/GMT+9",
        "Etc/GMT-0",
        "Etc/GMT-1",
        "Etc/GMT-10",
        "Etc/GMT-11",
        "Etc/GMT-12",
        "Etc/GMT-13",
        "Etc/GMT-14",
        "Etc/GMT-2",
        "Etc/GMT-3",
        "Etc/GMT-4",
        "Etc/GMT-5",
        "Etc/GMT-6",
        "Etc/GMT-7",
        "Etc/GMT-8",
        "Etc/GMT-9",
        "Etc/GMT0",
        "Etc/Greenwich",
        "Etc/UCT",
        "Etc/UTC",
        "Etc/Universal",
        "Etc/Zulu",
        "Europe/Amsterdam",
        "Europe/Andorra",
        "Europe/Astrakhan",
        "Europe/Athens",
        "Europe/Belfast",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Bratislava",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Budapest",
        "Europe/Busingen",
        "Europe/Chisinau",
        "Europe/Copenhagen",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Guernsey",
        "Europe/Helsinki",
        "Europe/Isle_of_Man",
        "Europe/Istanbul",
        "Europe/Jersey",
        "Europe/Kaliningrad",
        "Europe/Kiev",
        "Europe/Kirov",
        "Europe/Kyiv",
        "Europe/Lisbon",
        "Europe/Ljubljana",
        "Europe/London",
        "Europe/Luxembourg",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Mariehamn",
        "Europe/Minsk",
        "Europe/Monaco",
        "Europe/Moscow",
        "Europe/Nicosia",
        "Europe/Oslo",
        "Europe/Paris",
        "Europe/Podgorica",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/Samara",
        "Europe/San_Marino",
        "Europe/Sarajevo",
        "Europe/Saratov",
        "Europe/Simferopol",
        "Europe/Skopje",
        "Europe/Sofia",
        "Europe/Stockholm",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Tiraspol",
        "Europe/Ulyanovsk",
        "Europe/Uzhgorod",
        "Europe/Vaduz",
        "Europe/Vatican",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Warsaw",
        "Europe/Zagreb",
        "Europe/Zaporozhye",
        "Europe/Zurich",
        "GB",
        "GB-Eire",
        "GMT",
        "GMT+0",
        "GMT-0",
        "GMT0",
        "Greenwich",
        "HST",
        "Hongkong",
        "Iceland",
        "Indian/Antananarivo",
        "Indian/Chagos",
        "Indian/Christmas",
        "Indian/Cocos",
        "Indian/Comoro",
        "Indian/Kerguelen",
        "Indian/Mahe",
        "Indian/Maldives",
        "Indian/Mauritius",
        "Indian/Mayotte",
        "Indian/Reunion",
        "Iran",
        "Israel",
        "Jamaica",
        "Japan",
        "Kwajalein",
        "Libya",
        "MET",
        "MST",
        "MST7MDT",
        "Mexico/BajaNorte",
        "Mexico/BajaSur",
        "Mexico/General",
        "NZ",
        "NZ-CHAT",
        "Navajo",
        "PRC",
        "PST8PDT",
        "Pacific/Apia",
        "Pacific/Auckland",
        "Pacific/Bougainville",
        "Pacific/Chatham",
        "Pacific/Chuuk",
        "Pacific/Easter",
        "Pacific/Efate",
        "Pacific/Enderbury",
        "Pacific/Fakaofo",
        "Pacific/Fiji",
        "Pacific/Funafuti",
        "Pacific/Galapagos",
        "Pacific/Gambier",
        "Pacific/Guadalcanal",
        "Pacific/Guam",
        "Pacific/Honolulu",
        "Pacific/Johnston",
        "Pacific/Kanton",
        "Pacific/Kiritimati",
        "Pacific/Kosrae",
        "Pacific/Kwajalein",
        "Pacific/Majuro",
        "Pacific/Marquesas",
        "Pacific/Midway",
        "Pacific/Nauru",
        "Pacific/Niue",
        "Pacific/Norfolk",
        "Pacific/Noumea",
        "Pacific/Pago_Pago",
        "Pacific/Palau",
        "Pacific/Pitcairn",
        "Pacific/Pohnpei",
        "Pacific/Ponape",
        "Pacific/Port_Moresby",
        "Pacific/Rarotonga",
        "Pacific/Saipan",
        "Pacific/Samoa",
        "Pacific/Tahiti",
        "Pacific/Tarawa",
        "Pacific/Tongatapu",
        "Pacific/Truk",
        "Pacific/Wake",
        "Pacific/Wallis",
        "Pacific/Yap",
        "Poland",
        "Portugal",
        "ROC",
        "ROK",
        "Singapore",
        "Turkey",
        "UCT",
        "US/Alaska",
        "US/Aleutian",
        "US/Arizona",
        "US/Central",
        "US/East-Indiana",
        "US/Eastern",
        "US/Hawaii",
        "US/Indiana-Starke",
        "US/Michigan",
        "US/Mountain",
        "US/Pacific",
        "US/Samoa",
        "UTC",
        "Universal",
        "W-SU",
        "WET",
        "Zulu"
      ]
    },
    "type": "timezone",
    "component": "timezone",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.562Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f4680543b",
    "name": "reference_number",
    "label": "Reference number",
    "category": "Basic information",
    "schema": {
      "type": "string"
    },
    "type": "text",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.562Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f4680543c",
    "name": "description",
    "label": "Description",
    "category": "Basic information",
    "schema": {
      "type": "string"
    },
    "type": "description",
    "component": "textarea",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.563Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "63e50a55a2aaee1f4680543d",
    "name": "location",
    "label": "Location",
    "category": "Basic information",
    "schema": {
      "type": "string"
    },
    "type": "string",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "attributeTranslations": [],
    "created_at": "2023-02-09T14:59:33.563Z",
    "updated_at": "2025-08-27T13:08:09.413Z"
  },
  {
    "id": "6419c192698afd9226f1b820",
    "name": "long_text",
    "label": "Long Text",
    "category": "Basic information",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "type": "virtual-textarea",
    "component": "textarea",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": true,
    "builtin": true,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2023-03-21T14:39:14.719Z",
    "updated_at": "2024-06-17T11:17:10.635Z"
  },
  {
    "id": "64f86e7f66af8686895a41da",
    "name": "number_field",
    "label": "Number Field",
    "category": "Basic information",
    "schema": {
      "type": [
        "number",
        "null"
      ],
      "minimum": 2,
      "maximum": 8,
      "multipleOf": 1
    },
    "type": "number",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": true,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2023-09-06T12:20:15.231Z",
    "updated_at": "2023-11-14T09:18:50.298Z"
  },
  {
    "id": "677d2652b914dbdb1126771e",
    "name": "global_event_time",
    "label": "Global Event Time",
    "category": "Basic information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "time"
    },
    "type": "time",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2025-01-07T13:04:18.297Z",
    "updated_at": "2025-01-07T13:04:18.297Z"
  },
  {
    "id": "67d7e40a47ced642cb58afcc",
    "name": "event_url",
    "label": "Event URL",
    "category": "Basic information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "type": "url",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": true,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2025-03-17T08:57:46.255Z",
    "updated_at": "2025-03-17T08:57:46.255Z"
  },
  {
    "id": "64799ce67c94ef951ade7ed3",
    "name": "week_availability__local",
    "label": "Week Availability",
    "category": "Basic information",
    "schema": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Weekend",
          "Weekday"
        ]
      }
    },
    "type": "multi-select",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": false,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2023-06-02T07:40:22.564Z",
    "updated_at": "2025-03-07T06:20:06.089Z"
  },
  {
    "id": "66699eb824a8c2484825ee3f",
    "name": "date_time__local",
    "label": "Date-time",
    "category": "Basic information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "type": "datetime",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": false,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2024-06-12T13:12:24.629Z",
    "updated_at": "2024-06-12T14:04:07.215Z"
  },
  {
    "id": "6756bbe0a5e35bd19be60712",
    "name": "date_only__local",
    "label": "Date only",
    "category": "Basic information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date"
    },
    "type": "date",
    "component": "default",
    "archived": false,
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "builtin": false,
    "options": {},
    "attributeTranslations": [],
    "created_at": "2024-12-09T09:44:00.326Z",
    "updated_at": "2024-12-09T09:44:00.326Z"
  }
]

const participantFields = [
  {
    "id": "64145d385b5b378693fadacf",
    "name": "profile_page_id",
    "label": "Profile page",
    "crm_field_id": "63e50b2b8ba4c356d23fc3f0",
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[a-f0-9]{24}$"
    },
    "component": "relation",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "relation",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2025-02-20T14:15:47.940Z",
    "planners_only": true
  },
  {
    "id": "64145d385b5b378693fadad0",
    "name": "email",
    "label": "Email",
    "crm_field_id": "63e50b2b8ba4c356d23fc3f2",
    "category": "Personal information",
    "schema": {
      "type": "string",
      "format": "email",
      "minLength": 1
    },
    "component": "default",
    "mandatory_for_planners": true,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "string",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2025-04-11T17:10:28.920Z"
  },
  {
    "id": "64145d385b5b378693fadad1",
    "name": "preferred_language",
    "label": "Preferred language",
    "crm_field_id": "63e50b2b8ba4c356d23fc3f4",
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "aa",
        "aa-DJ",
        "aa-ER",
        "aa-ET",
        "af",
        "af-NA",
        "af-ZA",
        "agq",
        "agq-CM",
        "ak",
        "ak-GH",
        "sq",
        "sq-AL",
        "sq-MK",
        "gsw",
        "gsw-FR",
        "gsw-LI",
        "gsw-CH",
        "am",
        "am-ET",
        "ar",
        "ar-DZ",
        "ar-BH",
        "ar-TD",
        "ar-KM",
        "ar-DJ",
        "ar-EG",
        "ar-ER",
        "ar-IQ",
        "ar-IL",
        "ar-JO",
        "ar-KW",
        "ar-LB",
        "ar-LY",
        "ar-MR",
        "ar-MA",
        "ar-OM",
        "ar-PS",
        "ar-QA",
        "ar-SA",
        "ar-SO",
        "ar-SS",
        "ar-SD",
        "ar-SY",
        "ar-TN",
        "ar-AE",
        "ar-001",
        "ar-YE",
        "hy",
        "hy-AM",
        "as",
        "as-IN",
        "ast",
        "ast-ES",
        "asa",
        "asa-TZ",
        "az-Cyrl",
        "az-Cyrl-AZ",
        "az",
        "az-Latn",
        "az-Latn-AZ",
        "ksf",
        "ksf-CM",
        "bm",
        "bm-Latn-ML",
        "bn",
        "bn-BD",
        "bn-IN",
        "bas",
        "bas-CM",
        "ba",
        "ba-RU",
        "eu",
        "eu-ES",
        "be",
        "be-BY",
        "bem",
        "bem-ZM",
        "bez",
        "bez-TZ",
        "byn",
        "byn-ER",
        "brx",
        "brx-IN",
        "bs-Cyrl",
        "bs-Cyrl-BA",
        "bs-Latn",
        "bs",
        "bs-Latn-BA",
        "br",
        "br-FR",
        "bg",
        "bg-BG",
        "my",
        "my-MM",
        "ca",
        "ca-AD",
        "ca-FR",
        "ca-IT",
        "ca-ES",
        "ceb",
        "ceb-Latn",
        "ceb-Latn-PH",
        "tzm-Latn-",
        "ku",
        "ku-Arab",
        "ku-Arab-IQ",
        "ccp",
        "ccp-Cakm",
        "ccp-Cakm-",
        "cd-RU",
        "chr",
        "chr-Cher",
        "chr-Cher-US",
        "cgg",
        "cgg-UG",
        "zh-Hans",
        "zh",
        "zh-CN",
        "zh-SG",
        "zh-Hant",
        "zh-HK",
        "zh-MO",
        "zh-TW",
        "cu-RU",
        "swc",
        "swc-CD",
        "kw",
        "kw-GB",
        "co",
        "co-FR",
        "hr,",
        "hr-HR",
        "hr-BA",
        "cs",
        "cs-CZ",
        "da",
        "da-DK",
        "da-GL",
        "prs",
        "prs-AF",
        "dv",
        "dv-MV",
        "dua",
        "dua-CM",
        "nl",
        "nl-AW",
        "nl-BE",
        "nl-BQ",
        "nl-CW",
        "nl-NL",
        "nl-SX",
        "nl-SR",
        "dz",
        "dz-BT",
        "ebu",
        "ebu-KE",
        "en",
        "en-AS",
        "en-AI",
        "en-AG",
        "en-AU",
        "en-AT",
        "en-BS",
        "en-BB",
        "en-BE",
        "en-BZ",
        "en-BM",
        "en-BW",
        "en-IO",
        "en-VG",
        "en-BI",
        "en-CM",
        "en-CA",
        "en-029",
        "en-KY",
        "en-CX",
        "en-CC",
        "en-CK",
        "en-CY",
        "en-DK",
        "en-DM",
        "en-ER",
        "en-150",
        "en-FK",
        "en-FI",
        "en-FJ",
        "en-GM",
        "en-DE",
        "en-GH",
        "en-GI",
        "en-GD",
        "en-GU",
        "en-GG",
        "en-GY",
        "en-HK",
        "en-IN",
        "en-IE",
        "en-IM",
        "en-IL",
        "en-JM",
        "en-JE",
        "en-KE",
        "en-KI",
        "en-LS",
        "en-LR",
        "en-MO",
        "en-MG",
        "en-MW",
        "en-MY",
        "en-MT",
        "en-MH",
        "en-MU",
        "en-FM",
        "en-MS",
        "en-NA",
        "en-NR",
        "en-NL",
        "en-NZ",
        "en-NG",
        "en-NU",
        "en-NF",
        "en-MP",
        "en-PK",
        "en-PW",
        "en-PG",
        "en-PN",
        "en-PR",
        "en-PH",
        "en-RW",
        "en-KN",
        "en-LC",
        "en-VC",
        "en-WS",
        "en-SC",
        "en-SL",
        "en-SG",
        "en-SX",
        "en-SI",
        "en-SB",
        "en-ZA",
        "en-SS",
        "en-SH",
        "en-SD",
        "en-SZ",
        "en-SE",
        "en-CH",
        "en-TZ",
        "en-TK",
        "en-TO",
        "en-TT",
        "en-TC",
        "en-TV",
        "en-UG",
        "en-AE",
        "en-GB",
        "en-US",
        "en-UM",
        "en-VI",
        "en-VU",
        "en-001",
        "en-ZM",
        "en-ZW",
        "eo",
        "eo-001",
        "et",
        "et-EE",
        "ee",
        "ee-GH",
        "ee-TG",
        "ewo",
        "ewo-CM",
        "fo",
        "fo-DK",
        "fo-FO",
        "fil",
        "fil-PH",
        "fi",
        "fi-FI",
        "fr",
        "fr-DZ",
        "fr-BE",
        "fr-BJ",
        "fr-BF",
        "fr-BI",
        "fr-CM",
        "fr-CA",
        "fr-CF",
        "fr-TD",
        "fr-KM",
        "fr-CG",
        "fr-CD",
        "fr-CI",
        "fr-DJ",
        "fr-GQ",
        "fr-FR",
        "fr-GF",
        "fr-PF",
        "fr-GA",
        "fr-GP",
        "fr-GN",
        "fr-HT",
        "fr-LU",
        "fr-MG",
        "fr-ML",
        "fr-MQ",
        "fr-MR",
        "fr-MU",
        "fr-YT",
        "fr-MA",
        "fr-NC",
        "fr-NE",
        "fr-MC",
        "fr-RE",
        "fr-RW",
        "fr-BL",
        "fr-MF",
        "fr-PM",
        "fr-SN",
        "fr-SC",
        "fr-CH",
        "fr-SY",
        "fr-TG",
        "fr-TN",
        "fr-VU",
        "fr-WF",
        "fy",
        "fy-NL",
        "fur",
        "fur-IT",
        "ff",
        "ff-Latn",
        "ff-Latn-BF",
        "ff-CM",
        "ff-Latn-CM",
        "ff-Latn-GM",
        "ff-Latn-GH",
        "ff-GN",
        "ff-Latn-GN",
        "ff-Latn-GW",
        "ff-Latn-LR",
        "ff-MR",
        "ff-Latn-MR",
        "ff-Latn-NE",
        "ff-NG",
        "ff-Latn-NG",
        "ff-Latn-SN",
        "ff-Latn-SL",
        "gl",
        "gl-ES",
        "lg",
        "lg-UG",
        "ka",
        "ka-GE",
        "de",
        "de-AT",
        "de-BE",
        "de-DE",
        "de-IT",
        "de-LI",
        "de-LU",
        "de-CH",
        "el",
        "el-CY",
        "el-GR",
        "kl",
        "kl-GL",
        "gn",
        "gn-PY",
        "gu",
        "gu-IN",
        "guz",
        "guz-KE",
        "ha",
        "ha-Latn",
        "ha-Latn-GH",
        "ha-Latn-NE",
        "ha-Latn-NG",
        "haw",
        "haw-US",
        "he",
        "he-IL",
        "hi",
        "hi-IN",
        "hu",
        "hu-HU",
        "is",
        "is-IS",
        "ig",
        "ig-NG",
        "id",
        "id-ID",
        "ia",
        "ia-FR",
        "ia-001",
        "iu",
        "iu-Latn",
        "iu-Latn-CA",
        "iu-Cans",
        "iu-Cans-CA",
        "ga",
        "ga-IE",
        "it",
        "it-IT",
        "it-SM",
        "it-CH",
        "it-VA",
        "ja",
        "ja-JP",
        "jv",
        "jv-Latn",
        "jv-Latn-ID",
        "dyo",
        "dyo-SN",
        "kea",
        "kea-CV",
        "kab",
        "kab-DZ",
        "kkj",
        "kkj-CM",
        "kln",
        "kln-KE",
        "kam",
        "kam-KE",
        "kn",
        "kn-IN",
        "ks",
        "ks-Arab",
        "ks-Arab-IN",
        "kk",
        "kk-KZ",
        "km",
        "km-KH",
        "quc",
        "quc-Latn-GT",
        "ki",
        "ki-KE",
        "rw",
        "rw-RW",
        "sw",
        "sw-KE",
        "sw-TZ",
        "sw-UG",
        "kok",
        "kok-IN",
        "ko",
        "ko-KR",
        "ko-KP",
        "khq",
        "khq-ML",
        "ses",
        "ses-ML",
        "nmg",
        "nmg-CM",
        "ky",
        "ky-KG",
        "ku-Arab-IR",
        "lkt",
        "lkt-US",
        "lag",
        "lag-TZ",
        "lo",
        "lo-LA",
        "lv",
        "lv-LV",
        "ln",
        "ln-AO",
        "ln-CF",
        "ln-CG",
        "ln-CD",
        "lt",
        "lt-LT",
        "nds",
        "nds-DE",
        "nds-NL",
        "dsb",
        "dsb-DE",
        "lu",
        "lu-CD",
        "luo",
        "luo-KE",
        "lb",
        "lb-LU",
        "luy",
        "luy-KE",
        "mk",
        "mk-MK",
        "jmc",
        "jmc-TZ",
        "mgh",
        "mgh-MZ",
        "kde",
        "kde-TZ",
        "mg",
        "mg-MG",
        "ms",
        "ms-BN",
        "ms-MY",
        "ml",
        "ml-IN",
        "mt",
        "mt-MT",
        "gv",
        "gv-IM",
        "mi",
        "mi-NZ",
        "arn",
        "arn-CL",
        "mr",
        "mr-IN",
        "mas",
        "mas-KE",
        "mas-TZ",
        "mzn-IR",
        "mer",
        "mer-KE",
        "mgo",
        "mgo-CM",
        "moh",
        "moh-CA",
        "mn",
        "mn-Cyrl",
        "mn-MN",
        "mn-Mong",
        "mn-Mong-CN",
        "mn-Mong-MN",
        "mfe",
        "mfe-MU",
        "mua",
        "mua-CM",
        "nqo",
        "nqo-GN",
        "naq",
        "naq-NA",
        "ne",
        "ne-IN",
        "ne-NP",
        "nnh",
        "nnh-CM",
        "jgo",
        "jgo-CM",
        "lrc-IQ",
        "lrc-IR",
        "nd",
        "nd-ZW",
        "no",
        "nb",
        "nb-NO",
        "nn",
        "nn-NO",
        "nb-SJ",
        "nus",
        "nus-SD",
        "nus-SS",
        "nyn",
        "nyn-UG",
        "oc",
        "oc-FR",
        "or",
        "or-IN",
        "om",
        "om-ET",
        "om-KE",
        "os",
        "os-GE",
        "os-RU",
        "ps",
        "ps-AF",
        "ps-PK",
        "fa",
        "fa-AF",
        "fa-IR",
        "pl",
        "pl-PL",
        "pt",
        "pt-AO",
        "pt-BR",
        "pt-CV",
        "pt-GQ",
        "pt-GW",
        "pt-LU",
        "pt-MO",
        "pt-MZ",
        "pt-PT",
        "pt-ST",
        "pt-CH",
        "pt-TL",
        "prg-001",
        "qps-ploca",
        "qps-ploc",
        "qps-plocm",
        "pa",
        "pa-Arab",
        "pa-IN",
        "pa-Arab-PK",
        "quz",
        "quz-BO",
        "quz-EC",
        "quz-PE",
        "ksh",
        "ksh-DE",
        "ro",
        "ro-MD",
        "ro-RO",
        "rm",
        "rm-CH",
        "rof",
        "rof-TZ",
        "rn",
        "rn-BI",
        "ru",
        "ru-BY",
        "ru-KZ",
        "ru-KG",
        "ru-MD",
        "ru-RU",
        "ru-UA",
        "rwk",
        "rwk-TZ",
        "ssy",
        "ssy-ER",
        "sah",
        "sah-RU",
        "saq",
        "saq-KE",
        "smn",
        "smn-FI",
        "smj",
        "smj-NO",
        "smj-SE",
        "se",
        "se-FI",
        "se-NO",
        "se-SE",
        "sms",
        "sms-FI",
        "sma",
        "sma-NO",
        "sma-SE",
        "sg",
        "sg-CF",
        "sbp",
        "sbp-TZ",
        "sa",
        "sa-IN",
        "gd",
        "gd-GB",
        "seh",
        "seh-MZ",
        "sr-Cyrl",
        "sr-Cyrl-BA",
        "sr-Cyrl-ME",
        "sr-Cyrl-RS",
        "sr-Cyrl-CS",
        "sr-Latn",
        "sr",
        "sr-Latn-BA",
        "sr-Latn-ME",
        "sr-Latn-RS",
        "sr-Latn-CS",
        "nso",
        "nso-ZA",
        "tn",
        "tn-BW",
        "tn-ZA",
        "ksb",
        "ksb-TZ",
        "sn",
        "sn-Latn",
        "sn-Latn-ZW",
        "sd",
        "sd-Arab",
        "sd-Arab-PK",
        "si",
        "si-LK",
        "sk",
        "sk-SK",
        "sl",
        "sl-SI",
        "xog",
        "xog-UG",
        "so",
        "so-DJ",
        "so-ET",
        "so-KE",
        "so-SO",
        "st",
        "st-ZA",
        "nr",
        "nr-ZA",
        "st-LS",
        "es",
        "es-AR",
        "es-BZ",
        "es-VE",
        "es-BO",
        "es-BR",
        "es-CL",
        "es-CO",
        "es-CR",
        "es-CU",
        "es-DO",
        "es-EC",
        "es-SV",
        "es-GQ",
        "es-GT",
        "es-HN",
        "es-419",
        "es-MX",
        "es-NI",
        "es-PA",
        "es-PY",
        "es-PE",
        "es-PH",
        "es-PR",
        "es-ES_tradnl",
        "es-ES",
        "es-US",
        "es-UY",
        "zgh",
        "zgh-Tfng-MA",
        "zgh-Tfng",
        "ss",
        "ss-ZA",
        "ss-SZ",
        "sv",
        "sv-AX",
        "sv-FI",
        "sv-SE",
        "syr",
        "syr-SY",
        "shi",
        "shi-Tfng",
        "shi-Tfng-MA",
        "shi-Latn",
        "shi-Latn-MA",
        "dav",
        "dav-KE",
        "tg",
        "tg-Cyrl",
        "tg-Cyrl-TJ",
        "tzm",
        "tzm-Latn",
        "tzm-Latn-DZ",
        "ta",
        "ta-IN",
        "ta-MY",
        "ta-SG",
        "ta-LK",
        "twq",
        "twq-NE",
        "tt",
        "tt-RU",
        "te",
        "te-IN",
        "teo",
        "teo-KE",
        "teo-UG",
        "th",
        "th-TH",
        "bo",
        "bo-IN",
        "bo-CN",
        "tig",
        "tig-ER",
        "ti",
        "ti-ER",
        "ti-ET",
        "to",
        "to-TO",
        "ts",
        "ts-ZA",
        "tr",
        "tr-CY",
        "tr-TR",
        "tk",
        "tk-TM",
        "uk",
        "uk-UA",
        "hsb",
        "hsb-DE",
        "ur",
        "ur-IN",
        "ur-PK",
        "ug",
        "ug-CN",
        "uz-Arab",
        "uz-Arab-AF",
        "uz-Cyrl",
        "uz-Cyrl-UZ",
        "uz",
        "uz-Latn",
        "uz-Latn-UZ",
        "vai",
        "vai-Vaii",
        "vai-Vaii-LR",
        "vai-Latn-LR",
        "vai-Latn",
        "ca-ES-",
        "ve",
        "ve-ZA",
        "vi",
        "vi-VN",
        "vo",
        "vo-001",
        "vun",
        "vun-TZ",
        "wae",
        "wae-CH",
        "cy",
        "cy-GB",
        "wal",
        "wal-ET",
        "wo",
        "wo-SN",
        "xh",
        "xh-ZA",
        "yav",
        "yav-CM",
        "ii",
        "ii-CN",
        "yo",
        "yo-BJ",
        "yo-NG",
        "dje",
        "dje-NE",
        "zu",
        "zu-ZA"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "preference",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2023-09-13T12:16:09.908Z"
  },
  {
    "id": "64145d385b5b378693fadad2",
    "name": "crmstatus",
    "label": "Crm Status",
    "crm_field_id": "63e50b2b8ba4c356d23fc3f8",
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "new",
        "invited",
        "pending-approval",
        "declined",
        "registered",
        "registration-in-progress",
        "waitlist",
        "arrived",
        "no-show",
        "cancelled"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2023-03-17T12:29:44.163Z",
    "planners_only": true
  },
  {
    "id": "64145d385b5b378693fadad3",
    "name": "first_name",
    "label": "First name",
    "crm_field_id": "63e50b2b8ba4c356d23fc3fa",
    "category": "Personal information",
    "schema": {
      "type": "string"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "string",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2023-03-17T12:29:44.163Z"
  },
  {
    "id": "64145d385b5b378693fadad4",
    "name": "last_name",
    "label": "Last name",
    "crm_field_id": "63e50b2b8ba4c356d23fc3fe",
    "category": "Personal information",
    "schema": {
      "type": "string"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "string",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.581Z",
    "updated_at": "2023-03-17T12:29:44.163Z"
  },
  {
    "id": "64145d385b5b378693fadad5",
    "name": "organization_id",
    "label": "Company",
    "crm_field_id": "63e50b2b8ba4c356d23fc3fc",
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "relation",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "relation",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.581Z",
    "updated_at": "2023-03-17T12:29:44.163Z",
    "planners_only": true
  },
  {
    "id": "64145d385b5b378693fadad6",
    "name": "profile_image",
    "label": "Profile image",
    "crm_field_id": "63e50b2b8ba4c356d23fc400",
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[a-f0-9]{24}$"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "image",
    "builtin": true,
    "attributeTranslations": [],
    "options": {
      "aspect_ratio": 1,
      "maxHeight": 400,
      "maxWidth": 400
    },
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.581Z",
    "updated_at": "2023-03-17T12:29:44.163Z"
  },
  {
    "id": "64145d385b5b378693fadad7",
    "name": "organization_manager",
    "label": "Company manager",
    "crm_field_id": "63e50b2b8ba4c356d23fc3f6",
    "category": "Personal information",
    "schema": {
      "type": "boolean"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "boolean",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-02-09T15:03:07.580Z",
    "updated_at": "2023-03-17T12:29:44.163Z",
    "planners_only": true
  },
  {
    "id": "64145d385b5b378693fadad9",
    "name": "qrcode",
    "label": "QR Code",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "string",
    "builtin": true,
    "attributeTranslations": [],
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:29:44.726Z",
    "updated_at": "2023-03-17T12:29:44.726Z"
  },
  {
    "id": "64145d385b5b378693fadada",
    "name": "qrcode_on_badge",
    "label": "QR code on badge",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "string",
    "builtin": true,
    "attributeTranslations": [],
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:29:44.726Z",
    "updated_at": "2023-03-17T12:29:44.726Z"
  },
  {
    "id": "64145d3b103a8edfd98bec58",
    "name": "cancellation_reason",
    "label": "Cancellation reason",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "",
        "Business Reason",
        "Other Event",
        "Personal Reason"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:29:47.758Z",
    "updated_at": "2023-03-17T12:29:47.758Z"
  },
  {
    "id": "64145d3b103a8edfd98bec5d",
    "name": "decline_reason",
    "label": "Decline reason",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "",
        "Business Reason",
        "Other Event",
        "Personal Reason"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": false,
    "attributeTranslations": [
      {
        "value": "Business Reason",
        "trans": {
          "en-US": "Business Reason EN",
          "fr-FR": "Business Reason FR"
        }
      }
    ],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:29:47.944Z",
    "updated_at": "2025-06-20T14:00:21.482Z"
  },
  {
    "id": "64145d5208f721e83b5374fa",
    "name": "registrationtime__w",
    "label": "registrationtime",
    "crm_field_id": null,
    "category": "workflow",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "datetime",
    "builtin": false,
    "attributeTranslations": [],
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:30:10.339Z",
    "updated_at": "2025-08-04T23:04:33.066Z"
  },
  {
    "id": "64145d5908f721e83b537505",
    "name": "arrivaltime__w",
    "label": "arrivaltime",
    "crm_field_id": null,
    "category": "workflow",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "datetime",
    "builtin": false,
    "attributeTranslations": [],
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-17T12:30:17.245Z",
    "updated_at": "2025-08-04T23:04:32.684Z"
  },
  {
    "id": "6419c1428905c97a9394d44f",
    "name": "i_am_over_18_years_old__crm",
    "label": "I am over 18 years old",
    "crm_field_id": "6419c1428b7ab7162d1def1f",
    "category": "Personal information",
    "schema": {
      "type": [
        "boolean",
        "null"
      ],
      "default": false
    },
    "component": "default",
    "mandatory_for_planners": true,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "boolean",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-03-21T14:37:54.425Z",
    "updated_at": "2023-03-21T14:37:54.425Z"
  },
  {
    "id": "6479d0497c94ef951ade85ea",
    "name": "week_availability",
    "label": "Week Availability",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Weekday",
          "Weekend",
          "1",
          "2",
          "3",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10"
        ]
      }
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "multi-select",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-06-02T11:19:37.069Z",
    "updated_at": "2025-03-07T06:19:12.009Z"
  },
  {
    "id": "6490009f5fed0936095601f3",
    "name": "favorite_color",
    "label": "Favorite Color",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "",
        "Red",
        "Blue",
        "Green"
      ]
    },
    "component": "radio_buttons",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-06-19T07:15:43.565Z",
    "updated_at": "2024-11-01T13:47:27.634Z"
  },
  {
    "id": "6492e1c35fed093609563fe5",
    "name": "document",
    "label": "Document",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "document",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-06-21T11:40:51.053Z",
    "updated_at": "2023-06-21T11:40:51.053Z"
  },
  {
    "id": "6501a3686ba35b8e23486d30",
    "name": "new_select",
    "label": "New Select",
    "crm_field_id": null,
    "category": "",
    "schema": {
      "type": "string",
      "enum": [
        "1",
        "2",
        "3"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": false,
    "attributeTranslations": [
      {
        "value": "ERROR_MESSAGE_TRANSLATION",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      },
      {
        "value": "TOOLTIP_TRANSLATION",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      },
      {
        "value": "PLACEHOLDER_TRANSLATION",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      },
      {
        "value": "1",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      },
      {
        "value": "2",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      },
      {
        "value": "3",
        "trans": {
          "en-GB": "",
          "nl-NL": "",
          "fr-FR": "",
          "de-DE": "",
          "it-IT": "",
          "es-ES": ""
        }
      }
    ],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-09-13T11:56:24.820Z",
    "updated_at": "2023-09-13T11:56:24.820Z"
  },
  {
    "id": "651638fb7f9a80a1d650fc72",
    "name": "additional_info_68",
    "label": "Additional info &^68%&%$&(*&%$%&()&^$>:",
    "crm_field_id": null,
    "category": "",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "textarea",
    "mandatory_for_planners": true,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "virtual-textarea",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-09-29T02:39:55.706Z",
    "updated_at": "2023-12-13T03:01:47.718Z"
  },
  {
    "id": "652d236d45b2b354e6b4d87d",
    "name": "multiselect__crm",
    "label": "MUltiselect",
    "crm_field_id": "652d236d5bfe13997881cb9f",
    "category": "",
    "schema": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "",
          "One",
          "Two",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16"
        ]
      }
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "multi-select",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2023-10-16T11:50:05.051Z",
    "updated_at": "2023-12-06T03:16:40.779Z"
  },
  {
    "id": "66264ea399c88da49d1eb45c",
    "name": "newimage",
    "label": "NewImage",
    "crm_field_id": null,
    "category": "",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[a-f0-9]{24}$"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "image",
    "builtin": false,
    "attributeTranslations": [],
    "options": {
      "aspect_ratio": 0.6666,
      "maxWidth": 400,
      "maxHeight": 600,
      "cropping_mandatory": true
    },
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2024-04-22T11:48:51.152Z",
    "updated_at": "2024-04-22T11:52:51.573Z"
  },
  {
    "id": "66724d2532b55f385376db6b",
    "name": "document_upload__crm",
    "label": "Document Upload",
    "crm_field_id": "66724d25432a81998a505092",
    "category": "",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "document",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2024-06-19T03:14:45.492Z",
    "updated_at": "2024-06-19T03:14:45.492Z"
  },
  {
    "id": "6672f29233b8b23ff54d5ef8",
    "name": "aaada",
    "label": "AAAda ++",
    "crm_field_id": null,
    "category": "",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "text",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2024-06-19T15:00:34.817Z",
    "updated_at": "2024-09-09T13:24:42.299Z"
  },
  {
    "id": "667a98e5d2086d281656bf14",
    "name": "date_time",
    "label": "Date time",
    "crm_field_id": null,
    "category": "",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "datetime",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2024-06-25T10:16:05.583Z",
    "updated_at": "2024-06-25T10:16:05.583Z"
  },
  {
    "id": "679d04bff4503a0be0eb7a1c",
    "name": "select_eq_organization_field__crm",
    "label": "Select Eq Organization Field",
    "crm_field_id": "679d04be80218ba49bd719fd",
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "",
        "A"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-01-31T17:13:34.431Z",
    "updated_at": "2025-01-31T17:13:34.431Z"
  },
  {
    "id": "67dc2896a98afa8a76083a41",
    "name": "approver_email",
    "label": "Approver Email",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "email"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "email",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-03-20T14:39:18.850Z",
    "updated_at": "2025-03-20T14:39:18.850Z"
  },
  {
    "id": "67e456e6cad449719e381eee",
    "name": "yes_or_no",
    "label": "Yes Or No",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": "string",
      "enum": [
        "",
        "Yes",
        "No"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "select",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-03-26T19:35:02.081Z",
    "updated_at": "2025-03-26T19:35:25.194Z"
  },
  {
    "id": "6806ca0c5ea4f2241822ed5b",
    "name": "text__crm",
    "label": "Text",
    "crm_field_id": "6806ca0c4debf7b840ef64a9",
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "text",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-04-21T22:43:24.450Z",
    "updated_at": "2025-04-21T22:43:24.450Z"
  },
  {
    "id": "6824a0e12f6f1059888b9c39",
    "name": "integer",
    "label": "Integer",
    "crm_field_id": null,
    "category": "Personal information",
    "schema": {
      "type": [
        "integer",
        "null"
      ]
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": false,
    "visible_for_planners": true,
    "default_field": false,
    "type": "integer",
    "builtin": false,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-05-14T13:55:45.253Z",
    "updated_at": "2025-05-14T13:55:45.253Z"
  },
  {
    "id": "68309923aaecb722646ef501",
    "name": "global_datetime__crm",
    "label": "global datetime",
    "crm_field_id": "68309923843826306fe869c1",
    "category": "Personal information",
    "schema": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "datetime",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-05-23T15:49:55.639Z",
    "updated_at": "2025-05-23T15:49:55.639Z"
  },
  {
    "id": "689b5a30f2c20f71f43c265c",
    "name": "active__crm",
    "label": "Active",
    "crm_field_id": "689b5a2f11b63a6f02123f49",
    "category": "Personal information",
    "schema": {
      "type": "boolean"
    },
    "component": "default",
    "mandatory_for_planners": false,
    "locked_for_editing": true,
    "visible_for_planners": true,
    "default_field": false,
    "type": "boolean",
    "builtin": true,
    "attributeTranslations": [],
    "options": {},
    "placeholder": null,
    "tool_tip": null,
    "mask": null,
    "error_message": null,
    "created_at": "2025-08-12T15:13:51.943Z",
    "updated_at": "2025-08-12T15:13:51.970Z"
  }
]

export const metadata: PuckEditorMetadata<{}> = {
  dictionary,
  event,
  eventFields,
  languages,
  participant,
  participantFields,
  selectedLanguage: languages[0].id
}


export const DUMMY_ASSETS: Asset[] = [
  {
    id: '6853bcdcc483f61508cec49e',
    name: 'large image 1.png',
    content_type: 'image/png; charset=binary',
    file_size: 1794187,
    filename: 'large image 1.png',
    file_url: '/asset/6853bcdcc483f61508cec49e/large%20image%201.png',
    length: 1794187,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec49e/thumb.png',
    created_at: '2025-06-19T07:31:43.312Z',
    updated_at: '2025-06-19T07:31:43.312Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec49f',
    name: 'aza art.png',
    content_type: 'image/png; charset=binary',
    file_size: 41589,
    filename: 'aza art.png',
    file_url: '/asset/6853bcdcc483f61508cec49f/aza%20art.png',
    length: 41589,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec49f/thumb.png',
    created_at: '2025-06-19T07:31:43.323Z',
    updated_at: '2025-06-19T07:31:43.323Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a0',
    name: 'aza art crm.png',
    content_type: 'image/png; charset=binary',
    file_size: 21681,
    filename: 'aza art crm.png',
    file_url: '/asset/6853bcdcc483f61508cec4a0/aza%20art%20crm.png',
    length: 21681,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a0/thumb.png',
    created_at: '2025-06-19T07:31:43.335Z',
    updated_at: '2025-06-19T07:31:43.335Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a1',
    name: 'aza art2.png',
    content_type: 'image/png; charset=binary',
    file_size: 74096,
    filename: 'aza art2.png',
    file_url: '/asset/6853bcdcc483f61508cec4a1/aza%20art2.png',
    length: 74096,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a1/thumb.png',
    created_at: '2025-06-19T07:31:43.344Z',
    updated_at: '2025-06-19T07:31:43.344Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a2',
    name: 'Azavista - Border.png',
    content_type: 'image/png; charset=binary',
    file_size: 300162,
    filename: 'Azavista - Border.png',
    file_url: '/asset/6853bcdcc483f61508cec4a2/Azavista%20-%20Border.png',
    length: 300162,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a2/thumb.png',
    created_at: '2025-06-19T07:31:43.352Z',
    updated_at: '2025-06-19T07:31:43.352Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a3',
    name: '1. standard.png',
    content_type: 'image/png; charset=binary',
    file_size: 119740,
    filename: '1. standard.png',
    file_url: '/asset/6853bcdcc483f61508cec4a3/1.%20standard.png',
    length: 119740,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a3/thumb.png',
    created_at: '2025-06-19T07:31:43.383Z',
    updated_at: '2025-06-19T07:31:43.383Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a4',
    name: '2. first class.png',
    content_type: 'image/png; charset=binary',
    file_size: 237334,
    filename: '2. first class.png',
    file_url: '/asset/6853bcdcc483f61508cec4a4/2.%20first%20class.png',
    length: 237334,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a4/thumb.png',
    created_at: '2025-06-19T07:31:43.395Z',
    updated_at: '2025-06-19T07:31:43.395Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a5',
    name: '3. premium.png',
    content_type: 'image/png; charset=binary',
    file_size: 279566,
    filename: '3. premium.png',
    file_url: '/asset/6853bcdcc483f61508cec4a5/3.%20premium.png',
    length: 279566,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a5/thumb.png',
    created_at: '2025-06-19T07:31:43.415Z',
    updated_at: '2025-06-19T07:31:43.415Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a6',
    name: 'Location.png',
    content_type: 'image/png; charset=binary',
    file_size: 191455,
    filename: 'Location.png',
    file_url: '/asset/6853bcdcc483f61508cec4a6/Location.png',
    length: 191455,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a6/thumb.png',
    created_at: '2025-06-19T07:31:43.427Z',
    updated_at: '2025-06-19T07:31:43.427Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a7',
    name: 'Graphic.webp',
    content_type: 'image/webp; charset=binary',
    file_size: 28510,
    filename: 'Graphic.webp',
    file_url: '/asset/6853bcdcc483f61508cec4a7/Graphic.webp',
    length: 28510,
    'metadata.mime_type': 'image/webp; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a7/thumb.png',
    created_at: '2025-06-19T07:31:43.440Z',
    updated_at: '2025-06-19T07:31:43.440Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a8',
    name: 'Speaker 2.png',
    content_type: 'image/png; charset=binary',
    file_size: 1020518,
    filename: 'Speaker 2.png',
    file_url: '/asset/6853bcdcc483f61508cec4a8/Speaker%202.png',
    length: 1020518,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a8/thumb.png',
    created_at: '2025-06-19T07:31:43.450Z',
    updated_at: '2025-06-19T07:31:43.450Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4a9',
    name: 'Speaker 1.png',
    content_type: 'image/png; charset=binary',
    file_size: 579220,
    filename: 'Speaker 1.png',
    file_url: '/asset/6853bcdcc483f61508cec4a9/Speaker%201.png',
    length: 579220,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4a9/thumb.png',
    created_at: '2025-06-19T07:31:43.461Z',
    updated_at: '2025-06-19T07:31:43.461Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4aa',
    name: 'Speaker 3.png',
    content_type: 'image/png; charset=binary',
    file_size: 1232286,
    filename: 'Speaker 3.png',
    file_url: '/asset/6853bcdcc483f61508cec4aa/Speaker%203.png',
    length: 1232286,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4aa/thumb.png',
    created_at: '2025-06-19T07:31:43.474Z',
    updated_at: '2025-06-19T07:31:43.474Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4ab',
    name: 'org committee.png',
    content_type: 'image/png; charset=binary',
    file_size: 263749,
    filename: 'org committee.png',
    file_url: '/asset/6853bcdcc483f61508cec4ab/org%20committee.png',
    length: 263749,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4ab/thumb.png',
    created_at: '2025-06-19T07:31:43.483Z',
    updated_at: '2025-06-19T07:31:43.483Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4ac',
    name: 'Time schedule.png',
    content_type: 'image/png; charset=binary',
    file_size: 253094,
    filename: 'Time schedule.png',
    file_url: '/asset/6853bcdcc483f61508cec4ac/Time%20schedule.png',
    length: 253094,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4ac/thumb.png',
    created_at: '2025-06-19T07:31:43.493Z',
    updated_at: '2025-06-19T07:31:43.493Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4ad',
    name: 'Logo - Transparent.png',
    content_type: 'image/png; charset=binary',
    file_size: 95560,
    filename: 'Logo - Transparent.png',
    file_url: '/asset/6853bcdcc483f61508cec4ad/Logo%20-%20Transparent.png',
    length: 95560,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4ad/thumb.png',
    created_at: '2025-06-19T07:31:43.505Z',
    updated_at: '2025-06-19T07:31:43.505Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4ae',
    name: 'aza art8.png',
    content_type: 'image/png; charset=binary',
    file_size: 50882,
    filename: 'aza art8.png',
    file_url: '/asset/6853bcdcc483f61508cec4ae/aza%20art8.png',
    length: 50882,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4ae/thumb.png',
    created_at: '2025-06-19T07:31:43.514Z',
    updated_at: '2025-06-19T07:31:43.514Z',
    team_ids: [148],
  },
  {
    id: '6853bcdcc483f61508cec4af',
    name: 'aza art11.png',
    content_type: 'image/png; charset=binary',
    file_size: 43816,
    filename: 'aza art11.png',
    file_url: '/asset/6853bcdcc483f61508cec4af/aza%20art11.png',
    length: 43816,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/6853bcdcc483f61508cec4af/thumb.png',
    created_at: '2025-06-19T07:31:43.526Z',
    updated_at: '2025-06-19T07:31:43.526Z',
    team_ids: [148],
  },
  {
    id: '686b7e6ed72f860ec379dc0e',
    name: 'extension_100dp_000000_FILL0_wght400_GRAD0_opsz48.png',
    content_type: 'image/png; charset=binary',
    file_size: 1755,
    filename: 'extension_100dp_000000_FILL0_wght400_GRAD0_opsz48.png',
    file_url: '/asset/686b7e6ed72f860ec379dc0e/extension_100dp_000000_FILL0_wght400_GRAD0_opsz48.png',
    length: 1755,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686b7e6ed72f860ec379dc0e/thumb.png',
    created_at: '2025-07-07T07:59:43.428Z',
    updated_at: '2025-07-07T07:59:43.428Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e322',
    name: 'aza art crm.png',
    content_type: 'image/png; charset=binary',
    file_size: 21681,
    filename: 'aza art crm.png',
    file_url: '/asset/686ccb1cd72f860ec379e322/aza%20art%20crm.png',
    length: 21681,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e322/thumb.png',
    created_at: '2025-07-08T07:39:08.449Z',
    updated_at: '2025-07-08T07:39:08.449Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e324',
    name: 'aza art.png',
    content_type: 'image/png; charset=binary',
    file_size: 41589,
    filename: 'aza art.png',
    file_url: '/asset/686ccb1cd72f860ec379e324/aza%20art.png',
    length: 41589,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e324/thumb.png',
    created_at: '2025-07-08T07:39:08.508Z',
    updated_at: '2025-07-08T07:39:08.508Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e326',
    name: 'aza art2.png',
    content_type: 'image/png; charset=binary',
    file_size: 74096,
    filename: 'aza art2.png',
    file_url: '/asset/686ccb1cd72f860ec379e326/aza%20art2.png',
    length: 74096,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e326/thumb.png',
    created_at: '2025-07-08T07:39:08.587Z',
    updated_at: '2025-07-08T07:39:08.587Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e328',
    name: 'aza art3.png',
    content_type: 'image/png; charset=binary',
    file_size: 155752,
    filename: 'aza art3.png',
    file_url: '/asset/686ccb1cd72f860ec379e328/aza%20art3.png',
    length: 155752,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e328/thumb.png',
    created_at: '2025-07-08T07:39:08.631Z',
    updated_at: '2025-07-08T07:39:08.631Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e32a',
    name: 'aza art4.png',
    content_type: 'image/png; charset=binary',
    file_size: 40085,
    filename: 'aza art4.png',
    file_url: '/asset/686ccb1cd72f860ec379e32a/aza%20art4.png',
    length: 40085,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e32a/thumb.png',
    created_at: '2025-07-08T07:39:08.701Z',
    updated_at: '2025-07-08T07:39:08.701Z',
    team_ids: [148],
  },
  {
    id: '686ccb1cd72f860ec379e32c',
    name: 'aza art5.png',
    content_type: 'image/png; charset=binary',
    file_size: 41180,
    filename: 'aza art5.png',
    file_url: '/asset/686ccb1cd72f860ec379e32c/aza%20art5.png',
    length: 41180,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb1cd72f860ec379e32c/thumb.png',
    created_at: '2025-07-08T07:39:08.788Z',
    updated_at: '2025-07-08T07:39:08.788Z',
    team_ids: [148],
  },
  {
    id: '686ccb3bd72f860ec379e32e',
    name: 'Azavista - Background 35 opacity.png',
    content_type: 'image/png; charset=binary',
    file_size: 1515562,
    filename: 'Azavista - Background 35 opacity.png',
    file_url: '/asset/686ccb3bd72f860ec379e32e/Azavista%20-%20Background%2035%20opacity.png',
    length: 1515562,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb3bd72f860ec379e32e/thumb.png',
    created_at: '2025-07-08T07:39:39.855Z',
    updated_at: '2025-07-08T07:39:39.855Z',
    team_ids: [148],
  },
  {
    id: '686ccb3bd72f860ec379e335',
    name: 'Azavista - Background darker.png',
    content_type: 'image/png; charset=binary',
    file_size: 1417685,
    filename: 'Azavista - Background darker.png',
    file_url: '/asset/686ccb3bd72f860ec379e335/Azavista%20-%20Background%20darker.png',
    length: 1417685,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb3bd72f860ec379e335/thumb.png',
    created_at: '2025-07-08T07:39:40.001Z',
    updated_at: '2025-07-08T07:39:40.001Z',
    team_ids: [148],
  },
  {
    id: '686ccb3cd72f860ec379e33c',
    name: 'Azavista - Background lighter.png',
    content_type: 'image/png; charset=binary',
    file_size: 1624484,
    filename: 'Azavista - Background lighter.png',
    file_url: '/asset/686ccb3cd72f860ec379e33c/Azavista%20-%20Background%20lighter.png',
    length: 1624484,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb3cd72f860ec379e33c/thumb.png',
    created_at: '2025-07-08T07:39:40.149Z',
    updated_at: '2025-07-08T07:39:40.149Z',
    team_ids: [148],
  },
  {
    id: '686ccb3cd72f860ec379e344',
    name: 'Azavista - Background.png',
    content_type: 'image/png; charset=binary',
    file_size: 1419757,
    filename: 'Azavista - Background.png',
    file_url: '/asset/686ccb3cd72f860ec379e344/Azavista%20-%20Background.png',
    length: 1419757,
    'metadata.mime_type': 'image/png; charset=binary',
    thumbnail_url: '/asset/686ccb3cd72f860ec379e344/thumb.png',
    created_at: '2025-07-08T07:39:40.271Z',
    updated_at: '2025-07-08T07:39:40.271Z',
    team_ids: [148],
  },
  {
    id: '6870c6d2bf1f540d7cfc4b6b',
    name: '1. Simple Participant list.xlsx',
    content_type: 'application/zip; charset=binary',
    file_size: 8676,
    filename: '1. Simple Participant list.xlsx',
    file_url: '/asset/6870c6d2bf1f540d7cfc4b6b/1.%20Simple%20Participant%20list.xlsx',
    length: 8676,
    'metadata.mime_type': 'application/zip; charset=binary',
    thumbnail_url: '/asset/6870c6d2bf1f540d7cfc4b6b/thumb.png',
    created_at: '2025-07-11T08:09:54.689Z',
    updated_at: '2025-07-11T08:09:54.689Z',
    team_ids: [148],
  },
  {
    id: '6870c6d2bf1f540d7cfc4b6d',
    name: '2. 80 participants.xlsx',
    content_type: 'application/zip; charset=binary',
    file_size: 9955,
    filename: '2. 80 participants.xlsx',
    file_url: '/asset/6870c6d2bf1f540d7cfc4b6d/2.%2080%20participants.xlsx',
    length: 9955,
    'metadata.mime_type': 'application/zip; charset=binary',
    thumbnail_url: '/asset/6870c6d2bf1f540d7cfc4b6d/thumb.png',
    created_at: '2025-07-11T08:09:54.732Z',
    updated_at: '2025-07-11T08:09:54.732Z',
    team_ids: [148],
  },
  {
    id: '6870c6d2bf1f540d7cfc4b6f',
    name: 'Detailed Participant list.xlsx',
    content_type: 'application/zip; charset=binary',
    file_size: 9210,
    filename: 'Detailed Participant list.xlsx',
    file_url: '/asset/6870c6d2bf1f540d7cfc4b6f/Detailed%20Participant%20list.xlsx',
    length: 9210,
    'metadata.mime_type': 'application/zip; charset=binary',
    thumbnail_url: '/asset/6870c6d2bf1f540d7cfc4b6f/thumb.png',
    created_at: '2025-07-11T08:09:54.773Z',
    updated_at: '2025-07-11T08:09:54.773Z',
    team_ids: [148],
  },
]

